export type Student = {
  id: number;
  name: string;
  gender: "male" | "female";
  isBrushed: boolean;
  height: string;
  weight: string;
};

export type Class = Student[];

export type Grade = {
  [key: number]: Class;
};

export type School = {
  [key: number]: Grade;
};

export const SchoolAMock: School = {
  1: {
    1: [
      {
        id: 1,
        name: "정하율",
        gender: "female",
        isBrushed: true,
        height: "129",
        weight: "26kg",
      },
      {
        id: 2,
        name: "김도연",
        gender: "female",
        isBrushed: false,
        height: "131",
        weight: "29kg",
      },
      {
        id: 3,
        name: "이민우",
        gender: "male",
        isBrushed: true,
        height: "126",
        weight: "27kg",
      },
      {
        id: 4,
        name: "박수현",
        gender: "female",
        isBrushed: false,
        height: "123",
        weight: "25kg",
      },
      {
        id: 5,
        name: "최준호",
        gender: "male",
        isBrushed: true,
        height: "132",
        weight: "30kg",
      },
      {
        id: 6,
        name: "윤서준",
        gender: "male",
        isBrushed: false,
        height: "127",
        weight: "28kg",
      },
      {
        id: 7,
        name: "조예린",
        gender: "female",
        isBrushed: true,
        height: "125",
        weight: "26kg",
      },
    ],
    2: [
      {
        id: 8,
        name: "임하진",
        gender: "female",
        isBrushed: false,
        height: "130",
        weight: "27kg",
      },
      {
        id: 9,
        name: "장민재",
        gender: "male",
        isBrushed: true,
        height: "128",
        weight: "29kg",
      },
      {
        id: 10,
        name: "정다빈",
        gender: "female",
        isBrushed: true,
        height: "124",
        weight: "25kg",
      },
      {
        id: 11,
        name: "강지호",
        gender: "male",
        isBrushed: false,
        height: "129",
        weight: "30kg",
      },
      {
        id: 12,
        name: "이서윤",
        gender: "female",
        isBrushed: true,
        height: "126",
        weight: "28kg",
      },
    ],
    3: [
      {
        id: 13,
        name: "최하윤",
        gender: "female",
        isBrushed: false,
        height: "123",
        weight: "26kg",
      },
      {
        id: 14,
        name: "김예진",
        gender: "female",
        isBrushed: true,
        height: "125",
        weight: "27kg",
      },
      {
        id: 15,
        name: "박도훈",
        gender: "male",
        isBrushed: false,
        height: "128",
        weight: "28kg",
      },
      {
        id: 16,
        name: "윤하준",
        gender: "male",
        isBrushed: true,
        height: "130",
        weight: "29kg",
      },
      {
        id: 17,
        name: "정수아",
        gender: "female",
        isBrushed: true,
        height: "127",
        weight: "26kg",
      },
      {
        id: 18,
        name: "이준혁",
        gender: "male",
        isBrushed: false,
        height: "126",
        weight: "27kg",
      },
    ],
    4: [
      {
        id: 19,
        name: "조하린",
        gender: "female",
        isBrushed: true,
        height: "124",
        weight: "25kg",
      },
      {
        id: 20,
        name: "임시우",
        gender: "male",
        isBrushed: false,
        height: "129",
        weight: "30kg",
      },
      {
        id: 21,
        name: "장지유",
        gender: "female",
        isBrushed: true,
        height: "127",
        weight: "28kg",
      },
      {
        id: 22,
        name: "강민성",
        gender: "male",
        isBrushed: true,
        height: "131",
        weight: "31kg",
      },
      {
        id: 23,
        name: "이서하",
        gender: "female",
        isBrushed: false,
        height: "125",
        weight: "27kg",
      },
    ],
  },
  2: {
    1: [
      {
        id: 24,
        name: "김다은",
        gender: "female",
        isBrushed: true,
        height: "134",
        weight: "33kg",
      },
      {
        id: 25,
        name: "정하린",
        gender: "female",
        isBrushed: false,
        height: "132",
        weight: "32kg",
      },
      {
        id: 26,
        name: "박도윤",
        gender: "male",
        isBrushed: true,
        height: "133",
        weight: "34kg",
      },
      {
        id: 27,
        name: "이민재",
        gender: "male",
        isBrushed: true,
        height: "135",
        weight: "35kg",
      },
      {
        id: 28,
        name: "윤예빈",
        gender: "female",
        isBrushed: false,
        height: "131",
        weight: "31kg",
      },
    ],
    2: [
      {
        id: 29,
        name: "장준호",
        gender: "male",
        isBrushed: true,
        height: "136",
        weight: "36kg",
      },
      {
        id: 30,
        name: "임하윤",
        gender: "female",
        isBrushed: false,
        height: "132",
        weight: "33kg",
      },
      {
        id: 31,
        name: "조민서",
        gender: "female",
        isBrushed: true,
        height: "130",
        weight: "30kg",
      },
      {
        id: 32,
        name: "강도현",
        gender: "male",
        isBrushed: false,
        height: "133",
        weight: "34kg",
      },
      {
        id: 33,
        name: "이수빈",
        gender: "female",
        isBrushed: true,
        height: "131",
        weight: "32kg",
      },
      {
        id: 34,
        name: "최지호",
        gender: "male",
        isBrushed: true,
        height: "134",
        weight: "33kg",
      },
    ],
    3: [
      {
        id: 35,
        name: "정예린",
        gender: "female",
        isBrushed: false,
        height: "130",
        weight: "29kg",
      },
      {
        id: 36,
        name: "김민혁",
        gender: "male",
        isBrushed: true,
        height: "135",
        weight: "34kg",
      },
      {
        id: 37,
        name: "박하진",
        gender: "female",
        isBrushed: false,
        height: "132",
        weight: "31kg",
      },
      {
        id: 38,
        name: "윤시우",
        gender: "male",
        isBrushed: true,
        height: "134",
        weight: "33kg",
      },
      {
        id: 39,
        name: "이채원",
        gender: "female",
        isBrushed: true,
        height: "136",
        weight: "35kg",
      },
      {
        id: 40,
        name: "조도현",
        gender: "male",
        isBrushed: false,
        height: "137",
        weight: "36kg",
      },
      {
        id: 41,
        name: "임서윤",
        gender: "female",
        isBrushed: true,
        height: "133",
        weight: "32kg",
      },
    ],
  },
  3: {
    1: [
      {
        id: 42,
        name: "한서준",
        gender: "male",
        isBrushed: true,
        height: "137",
        weight: "36kg",
      },
      {
        id: 43,
        name: "문하영",
        gender: "female",
        isBrushed: false,
        height: "135",
        weight: "34kg",
      },
      {
        id: 44,
        name: "배민지",
        gender: "female",
        isBrushed: true,
        height: "138",
        weight: "35kg",
      },
      {
        id: 45,
        name: "송지훈",
        gender: "male",
        isBrushed: false,
        height: "136",
        weight: "37kg",
      },
      {
        id: 46,
        name: "강예원",
        gender: "female",
        isBrushed: true,
        height: "139",
        weight: "36kg",
      },
    ],
    2: [
      {
        id: 47,
        name: "신도윤",
        gender: "male",
        isBrushed: true,
        height: "140",
        weight: "38kg",
      },
      {
        id: 48,
        name: "남수아",
        gender: "female",
        isBrushed: false,
        height: "137",
        weight: "36kg",
      },
      {
        id: 49,
        name: "허진우",
        gender: "male",
        isBrushed: true,
        height: "139",
        weight: "37kg",
      },
      {
        id: 50,
        name: "정하은",
        gender: "female",
        isBrushed: true,
        height: "138",
        weight: "35kg",
      },
      {
        id: 51,
        name: "노지후",
        gender: "male",
        isBrushed: false,
        height: "141",
        weight: "38kg",
      },
    ],
    3: [
      {
        id: 52,
        name: "오채린",
        gender: "female",
        isBrushed: true,
        height: "136",
        weight: "34kg",
      },
      {
        id: 53,
        name: "구태윤",
        gender: "male",
        isBrushed: true,
        height: "137",
        weight: "35kg",
      },
      {
        id: 54,
        name: "백소율",
        gender: "female",
        isBrushed: false,
        height: "138",
        weight: "36kg",
      },
      {
        id: 55,
        name: "심재민",
        gender: "male",
        isBrushed: false,
        height: "140",
        weight: "37kg",
      },
      {
        id: 56,
        name: "채지안",
        gender: "female",
        isBrushed: true,
        height: "139",
        weight: "36kg",
      },
      {
        id: 57,
        name: "홍도현",
        gender: "male",
        isBrushed: true,
        height: "138",
        weight: "35kg",
      },
      {
        id: 58,
        name: "안하림",
        gender: "female",
        isBrushed: false,
        height: "136",
        weight: "33kg",
      },
    ],
  },
  4: {
    1: [
      {
        id: 59,
        name: "윤세은",
        gender: "female",
        isBrushed: true,
        height: "142",
        weight: "39kg",
      },
      {
        id: 60,
        name: "김지환",
        gender: "male",
        isBrushed: false,
        height: "144",
        weight: "41kg",
      },
      {
        id: 61,
        name: "장유진",
        gender: "female",
        isBrushed: true,
        height: "143",
        weight: "40kg",
      },
      {
        id: 62,
        name: "박태훈",
        gender: "male",
        isBrushed: true,
        height: "145",
        weight: "42kg",
      },
      {
        id: 63,
        name: "조서현",
        gender: "female",
        isBrushed: false,
        height: "141",
        weight: "38kg",
      },
    ],
    2: [
      {
        id: 64,
        name: "이재이",
        gender: "female",
        isBrushed: true,
        height: "143",
        weight: "39kg",
      },
      {
        id: 65,
        name: "정윤호",
        gender: "male",
        isBrushed: false,
        height: "146",
        weight: "42kg",
      },
      {
        id: 66,
        name: "한지후",
        gender: "male",
        isBrushed: true,
        height: "144",
        weight: "41kg",
      },
      {
        id: 67,
        name: "오세은",
        gender: "female",
        isBrushed: true,
        height: "142",
        weight: "40kg",
      },
      {
        id: 68,
        name: "문하진",
        gender: "female",
        isBrushed: false,
        height: "145",
        weight: "39kg",
      },
    ],
    3: [
      {
        id: 69,
        name: "송태윤",
        gender: "male",
        isBrushed: true,
        height: "146",
        weight: "42kg",
      },
      {
        id: 70,
        name: "백하은",
        gender: "female",
        isBrushed: true,
        height: "144",
        weight: "40kg",
      },
      {
        id: 71,
        name: "강지율",
        gender: "female",
        isBrushed: false,
        height: "142",
        weight: "38kg",
      },
      {
        id: 72,
        name: "허민준",
        gender: "male",
        isBrushed: false,
        height: "145",
        weight: "41kg",
      },
      {
        id: 73,
        name: "남예진",
        gender: "female",
        isBrushed: true,
        height: "143",
        weight: "39kg",
      },
    ],
  },

  5: {
    1: [
      {
        id: 74,
        name: "구하린",
        gender: "female",
        isBrushed: true,
        height: "148",
        weight: "43kg",
      },
      {
        id: 75,
        name: "노도현",
        gender: "male",
        isBrushed: false,
        height: "149",
        weight: "44kg",
      },
      {
        id: 76,
        name: "심지아",
        gender: "female",
        isBrushed: true,
        height: "147",
        weight: "42kg",
      },
      {
        id: 77,
        name: "오민재",
        gender: "male",
        isBrushed: false,
        height: "150",
        weight: "45kg",
      },
      {
        id: 78,
        name: "안채윤",
        gender: "female",
        isBrushed: true,
        height: "146",
        weight: "41kg",
      },
      {
        id: 79,
        name: "홍수진",
        gender: "female",
        isBrushed: false,
        height: "147",
        weight: "43kg",
      },
    ],
    2: [
      {
        id: 80,
        name: "백도윤",
        gender: "male",
        isBrushed: true,
        height: "149",
        weight: "44kg",
      },
      {
        id: 81,
        name: "채하은",
        gender: "female",
        isBrushed: true,
        height: "148",
        weight: "43kg",
      },
      {
        id: 82,
        name: "강세진",
        gender: "female",
        isBrushed: false,
        height: "147",
        weight: "42kg",
      },
      {
        id: 83,
        name: "이민호",
        gender: "male",
        isBrushed: false,
        height: "150",
        weight: "45kg",
      },
      {
        id: 84,
        name: "박하린",
        gender: "female",
        isBrushed: true,
        height: "149",
        weight: "43kg",
      },
    ],
    3: [
      {
        id: 85,
        name: "조유정",
        gender: "female",
        isBrushed: false,
        height: "148",
        weight: "42kg",
      },
      {
        id: 86,
        name: "임재현",
        gender: "male",
        isBrushed: true,
        height: "150",
        weight: "45kg",
      },
      {
        id: 87,
        name: "정나윤",
        gender: "female",
        isBrushed: true,
        height: "147",
        weight: "42kg",
      },
      {
        id: 88,
        name: "김현우",
        gender: "male",
        isBrushed: false,
        height: "149",
        weight: "44kg",
      },
      {
        id: 89,
        name: "윤세빈",
        gender: "female",
        isBrushed: true,
        height: "146",
        weight: "41kg",
      },
      {
        id: 90,
        name: "장민서",
        gender: "female",
        isBrushed: false,
        height: "148",
        weight: "43kg",
      },
    ],
  },
  6: {
    1: [
      {
        id: 91,
        name: "최지후",
        gender: "male",
        isBrushed: true,
        height: "153",
        weight: "47kg",
      },
      {
        id: 92,
        name: "조은서",
        gender: "female",
        isBrushed: false,
        height: "154",
        weight: "46kg",
      },
      {
        id: 93,
        name: "이도윤",
        gender: "male",
        isBrushed: true,
        height: "152",
        weight: "48kg",
      },
      {
        id: 94,
        name: "박예진",
        gender: "female",
        isBrushed: true,
        height: "155",
        weight: "49kg",
      },
      {
        id: 95,
        name: "정우진",
        gender: "male",
        isBrushed: false,
        height: "154",
        weight: "47kg",
      },
      {
        id: 96,
        name: "김하린",
        gender: "female",
        isBrushed: true,
        height: "153",
        weight: "45kg",
      },
    ],
    2: [
      {
        id: 97,
        name: "임서준",
        gender: "male",
        isBrushed: false,
        height: "155",
        weight: "48kg",
      },
      {
        id: 98,
        name: "강서아",
        gender: "female",
        isBrushed: true,
        height: "156",
        weight: "47kg",
      },
      {
        id: 99,
        name: "윤하늘",
        gender: "female",
        isBrushed: false,
        height: "154",
        weight: "46kg",
      },
      {
        id: 100,
        name: "장도윤",
        gender: "male",
        isBrushed: true,
        height: "157",
        weight: "49kg",
      },
      {
        id: 101,
        name: "이예은",
        gender: "female",
        isBrushed: true,
        height: "153",
        weight: "45kg",
      },
    ],
    3: [
      {
        id: 102,
        name: "조시우",
        gender: "male",
        isBrushed: false,
        height: "156",
        weight: "48kg",
      },
      {
        id: 103,
        name: "문지안",
        gender: "female",
        isBrushed: true,
        height: "155",
        weight: "47kg",
      },
      {
        id: 104,
        name: "노예림",
        gender: "female",
        isBrushed: true,
        height: "154",
        weight: "46kg",
      },
      {
        id: 105,
        name: "허재이",
        gender: "female",
        isBrushed: false,
        height: "153",
        weight: "45kg",
      },
      {
        id: 106,
        name: "남우주",
        gender: "male",
        isBrushed: true,
        height: "157",
        weight: "49kg",
      },
    ],
  },
};
