name: Deploy Chica

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Create .env file for build
        run: echo "${{ secrets.PROD_ENV }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Run prebuild script (prisma db pull + case format + generate)
        run: npm run prebuild

      - name: Build project (standalone)
        run: npm run build

      - name: Build batch script (compile TS to JS)
        run: npm run build:batch

      - name: Copy Prisma Client to standalone
        run: |
          mkdir -p .next/standalone/node_modules/.prisma
          cp -r node_modules/.prisma/client .next/standalone/node_modules/.prisma/client

          mkdir -p .next/standalone/node_modules/@prisma
          cp -r node_modules/@prisma/client .next/standalone/node_modules/@prisma/client

      - name: Compress standalone output
        run: |
          tar -czf standalone.tar.gz \
            .next/standalone \
            .next/static \
            public \
            package.json \
            next.config.ts \
            .env \
            dist

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "standalone.tar.gz"
          target: "~/deploy"

      - name: Deploy on EC2 and restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            export PATH="$NVM_DIR/versions/node/v22.11.0/bin:$PATH"
            mkdir -p ~/chica
            tar -xzf ~/deploy/standalone.tar.gz -C ~/chica --strip-components=0
            cd ~/chica
            pm2 delete chica || true
            pm2 start .next/standalone/server.js --name chica
            pm2 save
